import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import UiProvider from '@/lib/UiProvider';
import Header from '@/components/Header';
import './globals.css';
import { WalletProvider } from '@/lib/WalletProvider';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletProvider>
          <UiProvider>
            <Header />
            <main className="min-h-[calc(100vh-145px)] bg-gradient-to-br from-[#000000] from-60% via-[#18262f] via-70% to-[#301c47] to-90%">
              {children}
            </main>
            <Footer />
          </UiProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
